
development:
  adapter: postgresql
  encoding: utf8
  database: kakoona_app_development
  pool: 5
  host: localhost
  username: agentlogic
  password: Motiv88_


test:
  adapter: postgresql
  encoding: utf8
  database: kakoona_app_development
  pool: 5
  host: localhost
  username: agentlogic
  password: Motiv88_

production:
  adapter: postgresql
  database: db/kakoona_adportal_production
  pool: 5
  timeout: 5000