development:
  secret_key_base: 1ae4d5b01971a279da5769385f1b3cd42cd71fcccbb3a90da314deca47d6e5570a6c4480590300f2ab77aa0ab3808975928d17dde905fc2e639755d13af273e9
  aws:
    access_key_id: "AKIAJTK2DBXDDA5SVVLQ"
    secret_access_key: "jUFtShX5fknG7nMfPrLIlM+0xtQ3xdYqsSgjWUz"
    s3_bucket_name: "adportal-kakoona"
test:
  secret_key_base: 1ae4d5b01971a279da5769385f1b3cd42cd71fcccbb3a90da314deca47d6e5570a6c4480590300f2ab77aa0ab3808975928d17dde905fc2e639755d13af273e9
  aws:
    access_key_id: "AKIAJTK2DBXDDA5SVVLQ"
    secret_access_key: "jUFtShX5fknG7nMfPrLIlM+0xtQ3xdYqsSgjWUz"
    s3_bucket_name: "adportal-kakoona"
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws:
    access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
    secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
    s3_bucket_name: <%= ENV["S3_BUCKET_NAME"] %>