require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AdCampaignsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # AdCampaign. As you add validations to AdCampaign, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AdCampaignsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ad_campaigns as @ad_campaigns" do
      ad_campaign = AdCampaign.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:ad_campaigns)).to eq([ad_campaign])
    end
  end

  describe "GET show" do
    it "assigns the requested ad_campaign as @ad_campaign" do
      ad_campaign = AdCampaign.create! valid_attributes
      get :show, {:id => ad_campaign.to_param}, valid_session
      expect(assigns(:ad_campaign)).to eq(ad_campaign)
    end
  end

  describe "GET new" do
    it "assigns a new ad_campaign as @ad_campaign" do
      get :new, {}, valid_session
      expect(assigns(:ad_campaign)).to be_a_new(AdCampaign)
    end
  end

  describe "GET edit" do
    it "assigns the requested ad_campaign as @ad_campaign" do
      ad_campaign = AdCampaign.create! valid_attributes
      get :edit, {:id => ad_campaign.to_param}, valid_session
      expect(assigns(:ad_campaign)).to eq(ad_campaign)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AdCampaign" do
        expect {
          post :create, {:ad_campaign => valid_attributes}, valid_session
        }.to change(AdCampaign, :count).by(1)
      end

      it "assigns a newly created ad_campaign as @ad_campaign" do
        post :create, {:ad_campaign => valid_attributes}, valid_session
        expect(assigns(:ad_campaign)).to be_a(AdCampaign)
        expect(assigns(:ad_campaign)).to be_persisted
      end

      it "redirects to the created ad_campaign" do
        post :create, {:ad_campaign => valid_attributes}, valid_session
        expect(response).to redirect_to(AdCampaign.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ad_campaign as @ad_campaign" do
        post :create, {:ad_campaign => invalid_attributes}, valid_session
        expect(assigns(:ad_campaign)).to be_a_new(AdCampaign)
      end

      it "re-renders the 'new' template" do
        post :create, {:ad_campaign => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested ad_campaign" do
        ad_campaign = AdCampaign.create! valid_attributes
        put :update, {:id => ad_campaign.to_param, :ad_campaign => new_attributes}, valid_session
        ad_campaign.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested ad_campaign as @ad_campaign" do
        ad_campaign = AdCampaign.create! valid_attributes
        put :update, {:id => ad_campaign.to_param, :ad_campaign => valid_attributes}, valid_session
        expect(assigns(:ad_campaign)).to eq(ad_campaign)
      end

      it "redirects to the ad_campaign" do
        ad_campaign = AdCampaign.create! valid_attributes
        put :update, {:id => ad_campaign.to_param, :ad_campaign => valid_attributes}, valid_session
        expect(response).to redirect_to(ad_campaign)
      end
    end

    describe "with invalid params" do
      it "assigns the ad_campaign as @ad_campaign" do
        ad_campaign = AdCampaign.create! valid_attributes
        put :update, {:id => ad_campaign.to_param, :ad_campaign => invalid_attributes}, valid_session
        expect(assigns(:ad_campaign)).to eq(ad_campaign)
      end

      it "re-renders the 'edit' template" do
        ad_campaign = AdCampaign.create! valid_attributes
        put :update, {:id => ad_campaign.to_param, :ad_campaign => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ad_campaign" do
      ad_campaign = AdCampaign.create! valid_attributes
      expect {
        delete :destroy, {:id => ad_campaign.to_param}, valid_session
      }.to change(AdCampaign, :count).by(-1)
    end

    it "redirects to the ad_campaigns list" do
      ad_campaign = AdCampaign.create! valid_attributes
      delete :destroy, {:id => ad_campaign.to_param}, valid_session
      expect(response).to redirect_to(ad_campaigns_url)
    end
  end

end
