require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe MerchRepresentativesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # MerchRepresentative. As you add validations to MerchRepresentative, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MerchRepresentativesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all merch_representatives as @merch_representatives" do
      merch_representative = MerchRepresentative.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:merch_representatives)).to eq([merch_representative])
    end
  end

  describe "GET show" do
    it "assigns the requested merch_representative as @merch_representative" do
      merch_representative = MerchRepresentative.create! valid_attributes
      get :show, {:id => merch_representative.to_param}, valid_session
      expect(assigns(:merch_representative)).to eq(merch_representative)
    end
  end

  describe "GET new" do
    it "assigns a new merch_representative as @merch_representative" do
      get :new, {}, valid_session
      expect(assigns(:merch_representative)).to be_a_new(MerchRepresentative)
    end
  end

  describe "GET edit" do
    it "assigns the requested merch_representative as @merch_representative" do
      merch_representative = MerchRepresentative.create! valid_attributes
      get :edit, {:id => merch_representative.to_param}, valid_session
      expect(assigns(:merch_representative)).to eq(merch_representative)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MerchRepresentative" do
        expect {
          post :create, {:merch_representative => valid_attributes}, valid_session
        }.to change(MerchRepresentative, :count).by(1)
      end

      it "assigns a newly created merch_representative as @merch_representative" do
        post :create, {:merch_representative => valid_attributes}, valid_session
        expect(assigns(:merch_representative)).to be_a(MerchRepresentative)
        expect(assigns(:merch_representative)).to be_persisted
      end

      it "redirects to the created merch_representative" do
        post :create, {:merch_representative => valid_attributes}, valid_session
        expect(response).to redirect_to(MerchRepresentative.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved merch_representative as @merch_representative" do
        post :create, {:merch_representative => invalid_attributes}, valid_session
        expect(assigns(:merch_representative)).to be_a_new(MerchRepresentative)
      end

      it "re-renders the 'new' template" do
        post :create, {:merch_representative => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested merch_representative" do
        merch_representative = MerchRepresentative.create! valid_attributes
        put :update, {:id => merch_representative.to_param, :merch_representative => new_attributes}, valid_session
        merch_representative.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested merch_representative as @merch_representative" do
        merch_representative = MerchRepresentative.create! valid_attributes
        put :update, {:id => merch_representative.to_param, :merch_representative => valid_attributes}, valid_session
        expect(assigns(:merch_representative)).to eq(merch_representative)
      end

      it "redirects to the merch_representative" do
        merch_representative = MerchRepresentative.create! valid_attributes
        put :update, {:id => merch_representative.to_param, :merch_representative => valid_attributes}, valid_session
        expect(response).to redirect_to(merch_representative)
      end
    end

    describe "with invalid params" do
      it "assigns the merch_representative as @merch_representative" do
        merch_representative = MerchRepresentative.create! valid_attributes
        put :update, {:id => merch_representative.to_param, :merch_representative => invalid_attributes}, valid_session
        expect(assigns(:merch_representative)).to eq(merch_representative)
      end

      it "re-renders the 'edit' template" do
        merch_representative = MerchRepresentative.create! valid_attributes
        put :update, {:id => merch_representative.to_param, :merch_representative => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested merch_representative" do
      merch_representative = MerchRepresentative.create! valid_attributes
      expect {
        delete :destroy, {:id => merch_representative.to_param}, valid_session
      }.to change(MerchRepresentative, :count).by(-1)
    end

    it "redirects to the merch_representatives list" do
      merch_representative = MerchRepresentative.create! valid_attributes
      delete :destroy, {:id => merch_representative.to_param}, valid_session
      expect(response).to redirect_to(merch_representatives_url)
    end
  end

end
